# Computation on Numpy Arrays: Universal Functions

In [1]:
import numpy as np

In [2]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [4]:
print("x + 4 = ", x+4)
print(" x * 2 = ", x*2)
print("x - 5 = ", x-5)
print("x / 2 = ", x/2)
print("x // 2 = ", x//2)
print("-x = ", -x)
print("x ** 2 = ", x**2)
print("x % 5 = ", x%5)

x + 4 =  [4 5 6 7]
 x * 2 =  [0 2 4 6]
x - 5 =  [-5 -4 -3 -2]
x / 2 =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 5 =  [0 1 2 3]


In [5]:
(-0.5*x+1)**2

array([1.  , 0.25, 0.  , 0.25])

In [6]:
np.add(x, 2)

array([2, 3, 4, 5])