# 02.02 - The Basics of Numpy Arrays

In [1]:
import numpy as np
rng = np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [2]:
print(" one dimension array : x1 = ", x1)
print(" two dimension array : x2 = ", x2)
print(" three dimension array : x3 = ", x3)

 one dimension array : x1 =  [5 0 3 3 7 9]
 two dimension array : x2 =  [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
 three dimension array : x3 =  [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [7]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 type data: ", x3.dtype)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 type data:  int64


In [5]:
x1[1]

0

In [6]:
x2[1]

array([7, 6, 8, 8])

In [8]:
x3[1]

array([[0, 1, 9, 9, 0],
       [4, 7, 3, 2, 7],
       [2, 0, 0, 4, 5],
       [5, 6, 8, 4, 1]])

In [11]:
print("x3[1] shape: ", x3[1].shape)
print(f"x3[1] ndim: ", x3[1].ndim)
print(f"x3[1] size: {x3[1].size}")

x3[1] shape:  (4, 5)
x3[1] ndim:  2
x3[1] size: 20


In [12]:
x2[2, 0]

1

In [13]:
x3[0,2,1]

0

### Slicing : Accessing sub array

In [14]:
x1

array([5, 0, 3, 3, 7, 9])

In [15]:
x1[:3]

array([5, 0, 3])

In [16]:
x1[3:]

array([3, 7, 9])

In [17]:
x1[1:4]

array([0, 3, 3])

In [18]:
x1[::2]

array([5, 3, 7])

In [19]:
x1[1::2]

array([0, 3, 9])

In [22]:
x1[::-1] ## reversed

array([9, 7, 3, 3, 0, 5])

In [21]:
x1

array([5, 0, 3, 3, 7, 9])

In [23]:
x1[4::-2]

array([7, 3, 5])

In [25]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [24]:
x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]])

In [27]:
x2[::-1, ::-1] # all rows & columns, reversed

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [28]:
x2[0]

array([3, 5, 2, 4])

### Subarrays as No-Copy Views
> Unlike Python list slices, <span style="color:red">NumPy array slices are returned as views rather than copies </span> of the array data

In [29]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [33]:
x2_sub = x2[:2, :2] # let's extract 2 * 2 subarray from x2
print(x2_sub)

[[99  5]
 [ 7  6]]


In [34]:
x2_sub[0, 0] = 99 # let's modify this subarray
print(x2_sub)

[[99  5]
 [ 7  6]]


In [35]:
print(x2) # Now , we'll see that the original array is changed!

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
