## List in Python

In [26]:
L = list(range(11))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [27]:
type(L[0])

int

In [28]:
Lstr = [str(c) for c in L]

In [29]:
Lstr

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

In [30]:
type(Lstr[0])

str

In [31]:
L3 = [True, 1.05, 'coucou', 6, '7']
[type(c) for c in L3]

[bool, float, str, int, str]

## Fixed-type Arrays in Python

In [33]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Creating Arrays from Python Lists

In [21]:
import numpy as np

In [36]:
L1 = np.array([1, 2, 3, 6, 5, 4])
L1

array([1, 2, 3, 6, 5, 4])

In [41]:
L1.dtype

dtype('int64')

In [45]:
# upcast int to float implicitly
L2 =np.array([3.14, 4, 2, 3])
L2

array([3.14, 4.  , 2.  , 3.  ])

In [42]:
L2.dtype

dtype('float64')

In [46]:
# upcast int to float implicitly
L3 = np.array([3, 14.1, 4.0, 2.125, 3])
L3

array([ 3.   , 14.1  ,  4.   ,  2.125,  3.   ])

In [48]:
# upcast int to float explicitly using dtype
L4 = np.array([1, 2, 3, 4], dtype=np.float32)
L4

array([1., 2., 3., 4.], dtype=float32)

In [52]:
# nested lists result in multidimensional arrays
L5 = np.array([range(i, i + 3) for i in [2, 4, 6]])
L5

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

In [54]:
# Create a length-10 integer array filled with 0s
zeros_array = np.zeros(10, dtype=int)
zeros_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
# Create a 3 * 5 floating-point array filled with 1s
ones_array = np.ones((3, 5), dtype=float)
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
# Create a 3*5 array filled with 3.14
pi_array = np.full((3, 5), 3.14)
pi_array

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [58]:
# Create a 4 * 6 array filled with 2023
this_year_array = np.full((4, 6), 2023)
this_year_array

array([[2023, 2023, 2023, 2023, 2023, 2023],
       [2023, 2023, 2023, 2023, 2023, 2023],
       [2023, 2023, 2023, 2023, 2023, 2023],
       [2023, 2023, 2023, 2023, 2023, 2023]])

In [59]:
zeros_multi = np.zeros((4, 5), dtype=float)
zeros_multi

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
# Create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range function)
even_less_twenty = np.arange(0, 20, 2)
even_less_twenty

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
#create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [64]:
# create a 3 * 3 array of uniformly distributed
# pseudorandom values between 0 and 1
np.random.random((3, 3))

array([[0.28392893, 0.46573101, 0.61155583],
       [0.73153116, 0.75672968, 0.53732325],
       [0.8742884 , 0.43040906, 0.26720628]])

In [66]:
# Creater a 3 * 3 array of normally distributed pseudorandom
# values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.28320255, -1.32989219,  0.79358469],
       [ 0.9612432 ,  0.49796941, -0.75299144],
       [-0.70718374, -0.38359815, -0.89759007]])

In [67]:
# Create a 3 * 3 array of pseudorandom integers in the interval [0, 10]

In [68]:
np.random.randint(0, 10, (3, 3))

array([[3, 8, 7],
       [9, 9, 8],
       [9, 1, 0]])

In [69]:
# create a 3 * 3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
np.empty(3)

array([1., 1., 1.])